version: '3'
services:
  frontend-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: frontend-app
    ports:
      - '3000:3000'
    networks:
      - frontend-network
    volumes:
      - .:/app
networks:
  frontend-network:
    name: frontend_network
