#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo " Checking format, lint and types in your project before committing"

# Check Prettier standards
npm run check-format ||
(
    echo "Prettier Check Failed.  Run npm run format, add changes and try commit again.";
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
    echo "ESLint Check Failed.  Make the required changes listed above, add changes and try to commit again."
    false;
)

# Check tsconfig standards
npm run check-types ||
(
    echo "Type check Failed.  Make the changes required above."
    false;
)

# If everything passes... Now we can build
echo "All passed... Now we can build."

npm run build ||
(
    echo "Next build Failed. View the errors above to see why."
    false;
)

# If everything passes... Now we can commit
echo "Build is completed... I am committing this now. "
